-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.activation_codes
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    activation_code character varying NOT NULL,
    is_confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_codes_employers
(
    id integer NOT NULL,
    employers_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.activation_codes_jbseekers
(
    id integer NOT NULL,
    jbseekers_user_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    user_id integer NOT NULL,
    company_name character varying NOT NULL,
    website character varying NOT NULL,
    phone_number character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers_activation_by_staff
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    employers_id integer NOT NULL,
    staffs_id integer NOT NULL,
    is_confirmed boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    position_name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_seekers
(
    user_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    national_id character varying(11) NOT NULL,
    birth_year date NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.staffs
(
    user_id integer NOT NULL,
    first_name character varying NOT NULL,
    last_name character varying NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.activation_codes_employers
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.activation_codes_employers
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.activation_codes_jbseekers
    ADD FOREIGN KEY (id)
    REFERENCES public.activation_codes (id)
    NOT VALID;


ALTER TABLE public.activation_codes_jbseekers
    ADD FOREIGN KEY (id)
    REFERENCES public.job_seekers (user_id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_staff
    ADD FOREIGN KEY (employers_id)
    REFERENCES public.employers (user_id)
    NOT VALID;


ALTER TABLE public.employers_activation_by_staff
    ADD FOREIGN KEY (staffs_id)
    REFERENCES public.staffs (user_id)
    NOT VALID;


ALTER TABLE public.job_seekers
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.staffs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;